name: Cabinets update

on:
  schedule:
  - cron: "*/5 * * * *"


jobs:
  updating:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.DELAYED_JOB_CHECKOUT_REF }} # SHA that triggered your original job

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install libraries
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pyrebase
      - name: Run
        run: python scheduleParser.py

      # If job finished successfully, remove the workflow file (and tag if necessary)
      - name: Remove scheduled job
        uses: cardinalby/unschedule-job-action@v1
        with:
          ghToken: ${{ secrets.WORKFLOWS_TOKEN }}