name: Cabinets update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cardinalby/schedule-job-action@v1
        with:
          ghToken: ${{ secrets.WORKFLOWS_TOKEN }}
          templateYmlFile: '.github-scheduled-workflows/checks.yml'